### ISSUE TITLE
Solve issues with Github Action CI

### ISSUE THREAD

**Issue by davidrich27** [phylovi/bito#419]
Github Action CI `Run test` still fails on run.  Passes on Quokka and macOS environments.

**Comment by davidrich27** [comment]
The issues seem to arise from the version of the STL.  It may be that our doctests are presuming an ordering of unordered containers for golden tests.  

By selecting the version of GCC using this, our doctests pass.

```
- name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 7
          platform: x64
```
